name: SonarCloud

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read  # Required for SonarCloud
  id-token: write  # Optional, helps in debugging OpenID issues if needed

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    environment: development  # 👈 Add this line


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for full analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug - Check SONAR_TOKEN existence
        run: |
          echo "Checking if SONAR_TOKEN is set..."
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "❌ SONAR_TOKEN is NOT set or accessible in this context."
            exit 1
          else
            echo "✅ SONAR_TOKEN is set and available."
          fi

      - name: Debug - Print GitHub event info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: "-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}"

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
